language: ruby
rvm:
  - 1.9.3
  - 2.0.0

before_install:
  - gem update --system
  - gem --version

before_script:
  - cp config/database-travis.yml config/database.yml
  - cp config/secrets-travis.yml config/secrets.yml
  - rake db:setup
