language: ruby
bundler_args: --without development
rvm:
  - 1.9.3
  - 2.0.0
  - ruby-head

matrix:
  allow_failures:
    - rvm: ruby-head

before_install:
  - rvm rubygems current
  - gem --version
  - rvm list known
  - gem install brakeman

before_script:
  - cp config/database-travis.yml config/database.yml
  - cp config/secrets-travis.yml config/secrets.yml
  - mkdir -p tmp/backup
  - rake db:setup

after_script:
  - brakeman --format html --output brakeman.html --confidence-level 2
