language: ruby
rvm:
  - 1.9.3
  - 2.0.0

before_install:
  - gem update --system
  - gem --version

before_script:
  - cp config/secrets.yml.sample config/secrets.yml
  - cp config/database-travis.yml config/database.yml
  - psql -c 'create database thing_test;' -U postgres
